export const menuArray = [
    {
        name: "Pizza",
        id: 0,
        ingredients: ["pepperoni", "mushrom", "mozarella"],
        price: 14,
        emoji: "🍕",
        order_amount: 0,
        canceling_order: false,
    },
    {
        name: "Hamburger",
        id: 1,
        ingredients: ["beef", "cheese", "lettuce"],
        price: 12,
        emoji: "🍔",
        order_amount: 0,
        canceling_order: false,

    },
    {
        name: "Beer",
        ingredients: ["grain, hops, yeast, water"],
        id: 2,
        price: 12,
        emoji: "🍺",
        order_amount: 0,
        canceling_order: false,
    },
    {
        name: "coca cola",
        id: 3,
        ingredients: ["suger, hops, yeast, water"],
        price: 8,
        emoji: "🥤",
        order_amount: 0,
        canceling_order: false,
    },
    {
        name: "rice",
        id: 4,
        ingredients: ["oil, rice, carrote, water"],
        price: 20,
        emoji: "🍚",
        order_amount: 0,
        canceling_order: false,
    },
    {
        name: "meatball",
        id: 5,
        ingredients: ["oil, meat, onion, ---"],
        price: 20,
        emoji: "🧆",
        order_amount: 0,
        canceling_order: false,
    }
]